INSERT INTO country (name) VALUES ('Argentina');
INSERT INTO state (country_id, name) VALUES (1, 'Misiones');
INSERT INTO city (state_id, name) VALUES (1, '25 de Mayo')
INSERT INTO city (state_id, name) VALUES (1, 'Alba Posse')
INSERT INTO city (state_id, name) VALUES (1, 'Almafuerte')
INSERT INTO city (state_id, name) VALUES (1, 'Apóstoles')
INSERT INTO city (state_id, name) VALUES (1, 'Aristóbulo del Valle')
INSERT INTO city (state_id, name) VALUES (1, 'Arroyo del Medio')
INSERT INTO city (state_id, name) VALUES (1, 'Azara')
INSERT INTO city (state_id, name) VALUES (1, 'Bernardo de Irigoyen')
INSERT INTO city (state_id, name) VALUES (1, 'Bonpland')
INSERT INTO city (state_id, name) VALUES (1, 'Caá Yarí')
INSERT INTO city (state_id, name) VALUES (1, 'Campo Grande')
INSERT INTO city (state_id, name) VALUES (1, 'Campo Ramón')
INSERT INTO city (state_id, name) VALUES (1, 'Campo Viera')
INSERT INTO city (state_id, name) VALUES (1, 'Candelaria')
INSERT INTO city (state_id, name) VALUES (1, 'Capioví')
INSERT INTO city (state_id, name) VALUES (1, 'Caraguatay')
INSERT INTO city (state_id, name) VALUES (1, 'Cerro Azul')
INSERT INTO city (state_id, name) VALUES (1, 'Cerro Corá')
INSERT INTO city (state_id, name) VALUES (1, 'Colonia Alberdi')
INSERT INTO city (state_id, name) VALUES (1, 'Colonia Aurora')
INSERT INTO city (state_id, name) VALUES (1, 'Colonia Polana')
INSERT INTO city (state_id, name) VALUES (1, 'Colonia Victoria')
INSERT INTO city (state_id, name) VALUES (1, 'Comandante Andresito')
INSERT INTO city (state_id, name) VALUES (1, 'Concepción de la Sierra')
INSERT INTO city (state_id, name) VALUES (1, 'Corpus')
INSERT INTO city (state_id, name) VALUES (1, 'Dos Arroyos')
INSERT INTO city (state_id, name) VALUES (1, 'Dos de Mayo')
INSERT INTO city (state_id, name) VALUES (1, 'El Alcázar')
INSERT INTO city (state_id, name) VALUES (1, 'El Soberbio')
INSERT INTO city (state_id, name) VALUES (1, 'Eldorado')
INSERT INTO city (state_id, name) VALUES (1, 'Fachinal')
INSERT INTO city (state_id, name) VALUES (1, 'Florentino Ameghino')
INSERT INTO city (state_id, name) VALUES (1, 'Garuhapé')
INSERT INTO city (state_id, name) VALUES (1, 'Garupá')
INSERT INTO city (state_id, name) VALUES (1, 'General Alvear')
INSERT INTO city (state_id, name) VALUES (1, 'General Urquiza')
INSERT INTO city (state_id, name) VALUES (1, 'Gobernador López')
INSERT INTO city (state_id, name) VALUES (1, 'Gobernador Roca')
INSERT INTO city (state_id, name) VALUES (1, 'Guaraní')
INSERT INTO city (state_id, name) VALUES (1, 'Hipólito Yrigoyen')
INSERT INTO city (state_id, name) VALUES (1, 'Itacaruaré')
INSERT INTO city (state_id, name) VALUES (1, 'Jardín América')
INSERT INTO city (state_id, name) VALUES (1, 'Leandro N. Alem')
INSERT INTO city (state_id, name) VALUES (1, 'Loreto')
INSERT INTO city (state_id, name) VALUES (1, 'Los Helechos')
INSERT INTO city (state_id, name) VALUES (1, 'Mártires')
INSERT INTO city (state_id, name) VALUES (1, 'Mojón Grande')
INSERT INTO city (state_id, name) VALUES (1, 'Montecarlo')
INSERT INTO city (state_id, name) VALUES (1, 'Nueve de Julio')
INSERT INTO city (state_id, name) VALUES (1, 'Oberá')
INSERT INTO city (state_id, name) VALUES (1, 'Olegario Víctor Andrade')
INSERT INTO city (state_id, name) VALUES (1, 'Panambí')
INSERT INTO city (state_id, name) VALUES (1, 'Posadas')
INSERT INTO city (state_id, name) VALUES (1, 'Pozo Azul')
INSERT INTO city (state_id, name) VALUES (1, 'Profundidad')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Esperanza')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Iguazú')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Leoni')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Libertad')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Piray')
INSERT INTO city (state_id, name) VALUES (1, 'Puerto Rico')
INSERT INTO city (state_id, name) VALUES (1, 'Ruiz de Montoya')
INSERT INTO city (state_id, name) VALUES (1, 'Salto Encantado')
INSERT INTO city (state_id, name) VALUES (1, 'San Antonio')
INSERT INTO city (state_id, name) VALUES (1, 'San Ignacio')
INSERT INTO city (state_id, name) VALUES (1, 'San Javier')
INSERT INTO city (state_id, name) VALUES (1, 'San José')
INSERT INTO city (state_id, name) VALUES (1, 'San Martín')
INSERT INTO city (state_id, name) VALUES (1, 'San Pedro')
INSERT INTO city (state_id, name) VALUES (1, 'San Vicente')
INSERT INTO city (state_id, name) VALUES (1, 'Santa Ana')
INSERT INTO city (state_id, name) VALUES (1, 'Santa María')
INSERT INTO city (state_id, name) VALUES (1, 'Santiago de Liniers')
INSERT INTO city (state_id, name) VALUES (1, 'Santo Pipó')
INSERT INTO city (state_id, name) VALUES (1, 'Tres Capones')
INSERT INTO city (state_id, name) VALUES (1, 'Wanda')
