INSERT INTO country (name) VALUES ('ARGENTINA');
INSERT INTO state (country_id, name) VALUES (1, 'MISIONES');
INSERT INTO city (state_id, name) VALUES (1, 'ACARAGUA')
INSERT INTO city (state_id, name) VALUES (1, 'ALBA POSSE')
INSERT INTO city (state_id, name) VALUES (1, 'APOSTOLES')
INSERT INTO city (state_id, name) VALUES (1, 'ARISTOBULO DEL VALLE')
INSERT INTO city (state_id, name) VALUES (1, 'AZARA')
INSERT INTO city (state_id, name) VALUES (1, 'BARRA BONITA')
INSERT INTO city (state_id, name) VALUES (1, 'BARRA CONCEPCION')
INSERT INTO city (state_id, name) VALUES (1, 'BERNARDO DE IRIGOYEN')
INSERT INTO city (state_id, name) VALUES (1, 'CABURE')
INSERT INTO city (state_id, name) VALUES (1, 'CAMPO RAMON')
INSERT INTO city (state_id, name) VALUES (1, 'CAMPO VIERA')
INSERT INTO city (state_id, name) VALUES (1, 'CAPIOVI')
INSERT INTO city (state_id, name) VALUES (1, 'CAPIOVISIÑO')
INSERT INTO city (state_id, name) VALUES (1, 'CARAGUATAY')
INSERT INTO city (state_id, name) VALUES (1, 'CATARATAS DEL IGUAZU')
INSERT INTO city (state_id, name) VALUES (1, 'CERRO CORA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA ALICIA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA ALMAFUERTE')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA APOSTOLES')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA AURORA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA CAPON BONITO')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA CHAFARIZ')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA DELICIA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA EL PROGRESO')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA FINLANDESA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA FORTALEZA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA GRAMADO')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA GUARANI')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA LA GRUTA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA MARTIRES')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA ORO VERDE')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA POLANA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA PRIMAVERA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA ROCA CHICA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA SIETE ESTRELLAS')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA VICTORIA')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA YABEBIRI')
INSERT INTO city (state_id, name) VALUES (1, 'COMANDANTE ANDRESITO')
INSERT INTO city (state_id, name) VALUES (1, 'CONCEPCION DE LA SIERRA')
INSERT INTO city (state_id, name) VALUES (1, 'CORPUS')
INSERT INTO city (state_id, name) VALUES (1, 'CRUCE CABALLERO')
INSERT INTO city (state_id, name) VALUES (1, 'CUÑA PIRU')
INSERT INTO city (state_id, name) VALUES (1, 'DESEADO')
INSERT INTO city (state_id, name) VALUES (1, 'EL ALCAZAR')
INSERT INTO city (state_id, name) VALUES (1, 'EL SOBERBIO')
INSERT INTO city (state_id, name) VALUES (1, 'ELDORADO')
INSERT INTO city (state_id, name) VALUES (1, 'FACHINAL')
INSERT INTO city (state_id, name) VALUES (1, 'FRACRAN')
INSERT INTO city (state_id, name) VALUES (1, 'GARUHAPE')
INSERT INTO city (state_id, name) VALUES (1, 'GARUPA')
INSERT INTO city (state_id, name) VALUES (1, 'GOBERNADOR ROCA')
INSERT INTO city (state_id, name) VALUES (1, 'GUARAYPO')
INSERT INTO city (state_id, name) VALUES (1, 'GUAYABERA')
INSERT INTO city (state_id, name) VALUES (1, 'ISLA SAN LUCAS')
INSERT INTO city (state_id, name) VALUES (1, 'ITACARUARE')
INSERT INTO city (state_id, name) VALUES (1, 'ITAEMBRE MINI')
INSERT INTO city (state_id, name) VALUES (1, 'JARDIN AMERICA')
INSERT INTO city (state_id, name) VALUES (1, 'MBOPICUA')
INSERT INTO city (state_id, name) VALUES (1, 'MESA REDONDA')
INSERT INTO city (state_id, name) VALUES (1, 'MOCONA')
INSERT INTO city (state_id, name) VALUES (1, 'MOJON GRANDE')
INSERT INTO city (state_id, name) VALUES (1, 'OASIS')
INSERT INTO city (state_id, name) VALUES (1, 'OBERA')
INSERT INTO city (state_id, name) VALUES (1, 'PANAMBI')
INSERT INTO city (state_id, name) VALUES (1, 'PARADA LEIS')
INSERT INTO city (state_id, name) VALUES (1, 'PARAJE DOS HERMANAS')
INSERT INTO city (state_id, name) VALUES (1, 'PICADA GOBERNADOR LOPEZ')
INSERT INTO city (state_id, name) VALUES (1, 'PICADA LIBERTAD')
INSERT INTO city (state_id, name) VALUES (1, 'PINDAPOY')
INSERT INTO city (state_id, name) VALUES (1, 'PIÑALITO NORTE')
INSERT INTO city (state_id, name) VALUES (1, 'PIÑALITO SUR')
INSERT INTO city (state_id, name) VALUES (1, 'POSADAS')
INSERT INTO city (state_id, name) VALUES (1, 'PROFUNDIDAD')
INSERT INTO city (state_id, name) VALUES (1, 'PUEBLO SALTO')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO AZARA')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO IGUAZU')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO LAHARRAGUE')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO LEONI')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO LIBERTAD')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO MADO')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO PARANAY')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO PIRAY')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO RICO')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO VICTORIA')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO WANDA')
INSERT INTO city (state_id, name) VALUES (1, 'RUIZ DE MONTOYA')
INSERT INTO city (state_id, name) VALUES (1, 'SALTO ENCANTADO')
INSERT INTO city (state_id, name) VALUES (1, 'SAMAMBAYA')
INSERT INTO city (state_id, name) VALUES (1, 'SAN FRANCISCO DE ASIS')
INSERT INTO city (state_id, name) VALUES (1, 'SAN GOTARDO')
INSERT INTO city (state_id, name) VALUES (1, 'SANTIAGO DE LINIERS')
INSERT INTO city (state_id, name) VALUES (1, 'SANTO PIPO')
INSERT INTO city (state_id, name) VALUES (1, 'TARUMA')
INSERT INTO city (state_id, name) VALUES (1, 'TOBUNAS')
INSERT INTO city (state_id, name) VALUES (1, 'TORTA QUEMADA')
INSERT INTO city (state_id, name) VALUES (1, 'VILLA ARMONIA')
INSERT INTO city (state_id, name) VALUES (1, 'VILLA BONITA')
INSERT INTO city (state_id, name) VALUES (1, 'WANDA')
INSERT INTO city (state_id, name) VALUES (1, '2 DE MAYO')
INSERT INTO city (state_id, name) VALUES (1, '25 DE MAYO')
INSERT INTO city (state_id, name) VALUES (1, '3 DE MAYO')
INSERT INTO city (state_id, name) VALUES (1, '9 DE JULIO')
INSERT INTO city (state_id, name) VALUES (1, 'ARROYO DEL MEDIO')
INSERT INTO city (state_id, name) VALUES (1, 'BONPLAND')
INSERT INTO city (state_id, name) VALUES (1, 'CAMPO GRANDE')
INSERT INTO city (state_id, name) VALUES (1, 'CANDELARIA')
INSERT INTO city (state_id, name) VALUES (1, 'CERRO AZUL')
INSERT INTO city (state_id, name) VALUES (1, 'COLONIA ALBERDI')
INSERT INTO city (state_id, name) VALUES (1, 'DOS ARROYOS')
INSERT INTO city (state_id, name) VALUES (1, 'DOS HERMANAS')
INSERT INTO city (state_id, name) VALUES (1, 'EL PARAISO')
INSERT INTO city (state_id, name) VALUES (1, 'EL PORVENIR')
INSERT INTO city (state_id, name) VALUES (1, 'ESPERANZA')
INSERT INTO city (state_id, name) VALUES (1, 'FLORENTINO AMEGHINO')
INSERT INTO city (state_id, name) VALUES (1, 'GENERAL ALVEAR')
INSERT INTO city (state_id, name) VALUES (1, 'HIPOLITO YRIGOYEN')
INSERT INTO city (state_id, name) VALUES (1, 'LEANDRO N ALEM')
INSERT INTO city (state_id, name) VALUES (1, 'LOS HELECHOS')
INSERT INTO city (state_id, name) VALUES (1, 'MONTECARLO')
INSERT INTO city (state_id, name) VALUES (1, 'OLEGARIO VICTOR ANDRADE')
INSERT INTO city (state_id, name) VALUES (1, 'SAN ANTONIO')
INSERT INTO city (state_id, name) VALUES (1, 'SAN IGNACIO')
INSERT INTO city (state_id, name) VALUES (1, 'SAN JAVIER')
INSERT INTO city (state_id, name) VALUES (1, 'SAN JOSE')
INSERT INTO city (state_id, name) VALUES (1, 'SAN MARTIN')
INSERT INTO city (state_id, name) VALUES (1, 'SAN PEDRO')
INSERT INTO city (state_id, name) VALUES (1, 'SAN VICENTE')
INSERT INTO city (state_id, name) VALUES (1, 'SANTA ANA')
INSERT INTO city (state_id, name) VALUES (1, 'SANTA RITA')
INSERT INTO city (state_id, name) VALUES (1, 'TRES CAPONES')
INSERT INTO city (state_id, name) VALUES (1, 'VILLA LIBERTAD')
INSERT INTO city (state_id, name) VALUES (1, 'IMPORTACION - ARREGLAR')
INSERT INTO city (state_id, name) VALUES (1, 'VALLE HERMOSO')
INSERT INTO city (state_id, name) VALUES (1, 'POZO AZUL')
INSERT INTO city (state_id, name) VALUES (1, 'CAA YARI')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO BOSSETI')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO MANI')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO SANTA ANA')
INSERT INTO city (state_id, name) VALUES (1, 'PARAJE SAN ALBERTO')
INSERT INTO city (state_id, name) VALUES (1, 'PUERTO INTEGRACION')
INSERT INTO city (state_id, name) VALUES (1, 'PARAJE CAMPO ALEGRE')
INSERT INTO city (state_id, name) VALUES (1, 'PIRAY KM 18')
INSERT INTO city (state_id, name) VALUES (1, 'MARIANO NECOCHEA')

INSERT INTO "user" (username, password, email, first_name, last_name, education, skills, full_time, part_time, home_work, apply_for_job, disabled) VALUES ('admin', '$2a$10$lZJNipBMsZj7S6Wq5tTb8uw7yMaYNCpKcyuAMmlysCmZ2LjIzeiUm', 'email1', 'first_name1', 'last_name1', 'education1', 'skills1', true, false, false, true, false)

INSERT INTO "user" (username, password, email, first_name, last_name, education, skills, full_time, part_time, home_work, apply_for_job, disabled) VALUES ('user', '$2a$10$lZJNipBMsZj7S6Wq5tTb8uw7yMaYNCpKcyuAMmlysCmZ2LjIzeiUm', 'email2', 'first_name2', 'last_name2', 'education2', 'skills2', true, false, false, true, false)

INSERT INTO "user" (username, password, email, first_name, last_name, education, skills, full_time, part_time, home_work, apply_for_job, disabled) VALUES ('pepe', '$2a$10$lZJNipBMsZj7S6Wq5tTb8uw7yMaYNCpKcyuAMmlysCmZ2LjIzeiUm', 'email3', 'first_name3', 'last_name3', 'education3', 'skills3', true, false, false, true, false)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title1', 'description1', '2021-03-22 04:06:12', true, false, false, true, false, FALSE, 1)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title2', 'description2', '2021-03-22 04:06:12', false, true, false, true, false, FALSE, 1)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title3', 'description3', '2021-03-22 04:06:12', false, false, true, false, true, FALSE, 1)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title4', 'description4', '2021-03-22 04:06:12', true, false, false, true, false, FALSE, 1)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title5', 'description5', '2021-03-22 04:06:12', true, false, false, false, true, FALSE, 2)

INSERT INTO job (title, description, expiration, full_time, part_time, home_work, independent, dependent, disabled, user_id) VALUES ('title6', 'description6', '2021-03-22 04:06:12', false, false, true, true, false, FALSE, 2)

INSERT INTO contact (user_1_id, user_2_id) VALUES (1, 2)

INSERT INTO interest (user_id, job_id) VALUES (2, 2)

INSERT INTO interest (user_id, job_id) VALUES (2, 4)
